/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_hzbook_android_test_chapter9_rununit_MainActivity */

#ifndef _Included_cn_hzbook_android_test_chapter9_rununit_MainActivity
#define _Included_cn_hzbook_android_test_chapter9_rununit_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hzbook_android_test_chapter9_rununit_MainActivity
 * Method:    runUnitTests
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_hzbook_android_test_chapter9_rununit_MainActivity_runUnitTests
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
